// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC10GootenCore10GTNAddress")
@interface GTNAddress : NSObject
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull lastName;
@property (nonatomic, copy) NSString * _Nonnull line1;
@property (nonatomic, copy) NSString * _Nonnull line2;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
@property (nonatomic, copy) NSString * _Nonnull phone;
@property (nonatomic, copy) NSString * _Nonnull email;
@end

@class GTNProposedAddress;

SWIFT_CLASS("_TtC10GootenCore20GTNAddressValidation")
@interface GTNAddressValidation : NSObject
@property (nonatomic) BOOL isValid;
@property (nonatomic, copy) NSString * _Nonnull reason;
@property (nonatomic) NSInteger score;
@property (nonatomic, strong) GTNProposedAddress * _Nonnull proposedAddress;
@end

enum GTNEnvironment : NSInteger;

SWIFT_CLASS("_TtC10GootenCore9GTNConfig")
@interface GTNConfig : NSObject
@property (nonatomic) BOOL isInTestMode;
@property (nonatomic, copy) NSString * _Nonnull recipeId;
@property (nonatomic) BOOL turnOffLogs;
@property (nonatomic) enum GTNEnvironment environment;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull languageCode;
@property (nonatomic, copy) NSString * _Nonnull currencyCode;
@property (nonatomic) BOOL showAllProducts;
- (BOOL)isEqual:(id _Nullable)object;
@end

@class GTNError;
@class GTNProduct;
@class GTNProductVariant;
@class GTNSize;
@class GTNProductTemplate;
@class GTNShippingItem;
@class GTNShippingOption;
@class GTNShipPriceEstimate;
@class GTNOrderStatus;
@class PKPayment;
@class GTNPayment;
@class GTNOrderItem;
@class GTNPaymentBraintree;
@class GTNCountry;
@class GTNCurrency;
@class GTNUserInfo;
@class GTNPriceInfo;

SWIFT_CLASS("_TtC10GootenCore7GTNCore")
@interface GTNCore : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setConfig:(GTNConfig * _Nonnull)configuration;
- (GTNConfig * _Nonnull)config;
- (void)getUserLocationWithSuccess:(void (^ _Nonnull)(NSString * _Nonnull countryCode))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getProductsWithSuccess:(void (^ _Nonnull)(NSArray<GTNProduct *> * _Nonnull products))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getProductVariantsWithProductId:(NSInteger)productId success:(void (^ _Nonnull)(NSArray<GTNProductVariant *> * _Nonnull variants))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getRequiredImagesWithSku:(NSString * _Nonnull)sku templateName:(NSString * _Nonnull)templateName success:(void (^ _Nonnull)(NSArray<GTNSize *> * _Nonnull sizes))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getProductTemplatesWithSku:(NSString * _Nonnull)sku success:(void (^ _Nonnull)(NSArray<GTNProductTemplate *> * _Nonnull templates))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getShippingOptionsWithPostalCode:(NSString * _Nonnull)postalCode state:(NSString * _Nonnull)state countryCode:(NSString * _Nonnull)countryCode items:(NSArray<GTNShippingItem *> * _Nonnull)items success:(void (^ _Nonnull)(NSArray<GTNShippingOption *> * _Nonnull options))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getShipPriceEstimateWithProductId:(NSInteger)productId success:(void (^ _Nonnull)(GTNShipPriceEstimate * _Nonnull shipPriceEstimate))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getPaymentValidationWithOrderId:(NSString * _Nonnull)orderId paypalKey:(NSString * _Nonnull)paypalKey success:(void (^ _Nonnull)(BOOL isValid))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getOrderStatusWithOrderId:(NSString * _Nonnull)orderId success:(void (^ _Nonnull)(GTNOrderStatus * _Nonnull orderStatus))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)orderSubmitApplePayWithShippingAddress:(GTNAddress * _Nonnull)shippingAddress billingAddress:(GTNAddress * _Nonnull)billingAddress pkPayment:(PKPayment * _Nonnull)pkPayment payment:(GTNPayment * _Nonnull)payment items:(NSArray<GTNOrderItem *> * _Nonnull)items couponCodes:(NSArray<NSString *> * _Nonnull)couponCodes success:(void (^ _Nonnull)(NSString * _Nonnull orderId))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)orderSubmitBraintreeWithShippingAddress:(GTNAddress * _Nonnull)shippingAddress billingAddress:(GTNAddress * _Nonnull)billingAddress payment:(GTNPaymentBraintree * _Nonnull)payment items:(NSArray<GTNOrderItem *> * _Nonnull)items couponCodes:(NSArray<NSString *> * _Nonnull)couponCodes success:(void (^ _Nonnull)(NSString * _Nonnull orderId))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)orderSubmitPaypalWithShippingAddress:(GTNAddress * _Nonnull)shippingAddress payment:(GTNPayment * _Nonnull)payment items:(NSArray<GTNOrderItem *> * _Nonnull)items couponCodes:(NSArray<NSString *> * _Nonnull)couponCodes success:(void (^ _Nonnull)(NSString * _Nonnull orderId))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getCountriesWithSuccess:(void (^ _Nonnull)(NSArray<GTNCountry *> * _Nonnull countries))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getCurrenciesWithSuccess:(void (^ _Nonnull)(NSArray<GTNCurrency *> * _Nonnull currencies))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)getUserInfoWithSuccess:(void (^ _Nonnull)(GTNUserInfo * _Nonnull userInfo))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)convertCurrencyFromCurrencyCode:(NSString * _Nonnull)fromCurrencyCode toCurrencyCode:(NSString * _Nonnull)toCurrencyCode amount:(double)amount success:(void (^ _Nonnull)(GTNPriceInfo * _Nonnull result))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
- (void)validateAddress:(GTNAddress * _Nonnull)address success:(void (^ _Nonnull)(GTNAddressValidation * _Nonnull result))success failure:(void (^ _Nonnull)(GTNError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC10GootenCore10GTNCountry")
@interface GTNCountry : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) BOOL isSupported;
@property (nonatomic, copy) NSString * _Nonnull measurementCode;
@property (nonatomic, copy) NSString * _Nonnull flagUrl;
@property (nonatomic, strong) GTNCurrency * _Nonnull defaultCurrency;
@end


SWIFT_CLASS("_TtC10GootenCore11GTNCurrency")
@interface GTNCurrency : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull format;
@end

typedef SWIFT_ENUM(NSInteger, GTNEnvironment) {
  GTNEnvironmentProduction = 0,
  GTNEnvironmentStaging = 1,
  GTNEnvironmentQA = 2,
};

enum GTNErrorCode : NSInteger;

SWIFT_CLASS("_TtC10GootenCore8GTNError")
@interface GTNError : NSObject
@property (nonatomic) enum GTNErrorCode errorCode;
- (NSString * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, GTNErrorCode) {
  GTNErrorCodeInvalidURL = 0,
  GTNErrorCodeInvalidTemplate = 1,
  GTNErrorCodeNoInternetConnection = 2,
  GTNErrorCodeNoResponseFromServer = 3,
  GTNErrorCodeNoItems = 4,
  GTNErrorCodeParseJSONFailed = 5,
  GTNErrorCodeCustom = 6,
  GTNErrorCodeInvalidConfiguration = 7,
};


SWIFT_CLASS("_TtC10GootenCore8GTNLayer")
@interface GTNLayer : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic) NSInteger zIndex;
@property (nonatomic) NSInteger X1;
@property (nonatomic) NSInteger X2;
@property (nonatomic) NSInteger Y1;
@property (nonatomic) NSInteger Y2;
@property (nonatomic, copy) NSString * _Nonnull backgroundImageUrl;
@property (nonatomic, copy) NSString * _Nonnull overlayImageUrl;
@property (nonatomic) BOOL includeInPrint;
@property (nonatomic, copy) NSString * _Nonnull imageFill;
@property (nonatomic, copy) NSString * _Nonnull color;
@property (nonatomic, copy) NSString * _Nonnull fontName;
@property (nonatomic) double fontSize;
@property (nonatomic, copy) NSString * _Nonnull horizontalAlignment;
@property (nonatomic, copy) NSString * _Nonnull verticalAlignment;
@property (nonatomic, copy) NSString * _Nonnull defaultText;
@end

@class GTNOrderItemImage;

SWIFT_CLASS("_TtC10GootenCore12GTNOrderItem")
@interface GTNOrderItem : NSObject
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic) NSInteger quantity;
@property (nonatomic) NSInteger shipCarrierMethod;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull meta;
@property (nonatomic, copy) NSArray<GTNOrderItemImage *> * _Nonnull images;
@end


SWIFT_CLASS("_TtC10GootenCore17GTNOrderItemImage")
@interface GTNOrderItemImage : NSObject
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic) NSInteger index;
@property (nonatomic, copy) NSString * _Nonnull thumbnailUrl;
@property (nonatomic, copy) NSString * _Nonnull manipCommand;
@end

@class GTNOrderStatusItem;

SWIFT_CLASS("_TtC10GootenCore14GTNOrderStatus")
@interface GTNOrderStatus : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull niceId;
@property (nonatomic, copy) NSString * _Nonnull sourceId;
@property (nonatomic, copy) NSArray<GTNOrderStatusItem *> * _Nonnull items;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull total;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull shippingTotal;
@property (nonatomic, strong) GTNAddress * _Nonnull shippingAddress;
@property (nonatomic, strong) GTNAddress * _Nonnull billingAddress;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull meta;
@end


SWIFT_CLASS("_TtC10GootenCore18GTNOrderStatusItem")
@interface GTNOrderStatusItem : NSObject
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic) NSInteger productId;
@property (nonatomic, copy) NSString * _Nonnull product;
@property (nonatomic) NSInteger quantity;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull price;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull discountAmount;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull meta;
@property (nonatomic, copy) NSArray * _Nonnull shipments;
@end


SWIFT_CLASS("_TtC10GootenCore10GTNPayment")
@interface GTNPayment : NSObject
@property (nonatomic, copy) NSString * _Nonnull currencyCode;
@property (nonatomic) double total;
@end


SWIFT_CLASS("_TtC10GootenCore19GTNPaymentBraintree")
@interface GTNPaymentBraintree : GTNPayment
@property (nonatomic, copy) NSString * _Nonnull braintreeEncryptedCCNumber;
@property (nonatomic, copy) NSString * _Nonnull braintreeEncryptedCCExpDate;
@property (nonatomic, copy) NSString * _Nonnull braintreeEncryptedCCV;
@end


SWIFT_CLASS("_TtC10GootenCore12GTNPriceInfo")
@interface GTNPriceInfo : NSObject
@property (nonatomic) double price;
@property (nonatomic, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, copy) NSString * _Nonnull formattedPrice;
@property (nonatomic, copy) NSString * _Nonnull currencyFormat;
@property (nonatomic) NSInteger currencyDigits;
@end

@class GTNProductInfo;
@class GTNProductImage;
@class GTNProductCategory;

SWIFT_CLASS("_TtC10GootenCore10GTNProduct")
@interface GTNProduct : NSObject
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull uId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull shortDescription;
@property (nonatomic) BOOL hasAvailableProductVariants;
@property (nonatomic) BOOL hasProductTemplates;
@property (nonatomic) BOOL isFeatured;
@property (nonatomic) BOOL isComingSoon;
@property (nonatomic) double maxZoom;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull retailPrice;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull priceInfo;
@property (nonatomic, copy) NSArray<GTNProductInfo *> * _Nonnull info;
@property (nonatomic, copy) NSArray<GTNProductImage *> * _Nonnull images;
@property (nonatomic, copy) NSArray<GTNProductCategory *> * _Nonnull categories;
@end


SWIFT_CLASS("_TtC10GootenCore18GTNProductCategory")
@interface GTNProductCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger id;
@end


SWIFT_CLASS("_TtC10GootenCore15GTNProductImage")
@interface GTNProductImage : NSObject
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic) NSInteger index;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull types;
@end


SWIFT_CLASS("_TtC10GootenCore14GTNProductInfo")
@interface GTNProductInfo : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull content;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic) NSInteger index;
@end

@class GTNSpace;

SWIFT_CLASS("_TtC10GootenCore18GTNProductTemplate")
@interface GTNProductTemplate : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic) BOOL isDefault;
@property (nonatomic, copy) NSArray<GTNSpace *> * _Nonnull spaces;
@end

@class GTNVariantOption;

SWIFT_CLASS("_TtC10GootenCore17GTNProductVariant")
@interface GTNProductVariant : NSObject
@property (nonatomic, copy) NSArray<GTNVariantOption *> * _Nonnull options;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull priceInfo;
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic) NSInteger maxImages;
@property (nonatomic) BOOL hasTemplates;
@end


SWIFT_CLASS("_TtC10GootenCore18GTNProposedAddress")
@interface GTNProposedAddress : NSObject
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
@property (nonatomic, copy) NSString * _Nonnull stateOrProvinceCode;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull streetLines;
@end


SWIFT_CLASS("_TtC10GootenCore20GTNShipPriceEstimate")
@interface GTNShipPriceEstimate : NSObject
@property (nonatomic, strong) GTNPriceInfo * _Nonnull minPrice;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull maxPrice;
@property (nonatomic, copy) NSString * _Nonnull vendorCountryCode;
@property (nonatomic) BOOL canShipExpedited;
@property (nonatomic) NSInteger estShipDays;
@end


SWIFT_CLASS("_TtC10GootenCore15GTNShippingItem")
@interface GTNShippingItem : NSObject
@property (nonatomic, copy) NSString * _Nonnull sku;
@property (nonatomic) NSInteger quantity;
- (nonnull instancetype)initWithSku:(NSString * _Nonnull)skuS quantity:(NSInteger)quantity OBJC_DESIGNATED_INITIALIZER;
@end

@class GTNSingleShipOption;

SWIFT_CLASS("_TtC10GootenCore17GTNShippingOption")
@interface GTNShippingOption : NSObject
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull skus;
@property (nonatomic, copy) NSArray<GTNSingleShipOption *> * _Nonnull shipOptions;
@end


SWIFT_CLASS("_TtC10GootenCore19GTNSingleShipOption")
@interface GTNSingleShipOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull carrierName;
@property (nonatomic, copy) NSString * _Nonnull methodType;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) GTNPriceInfo * _Nonnull price;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger estBusinessDaysTilDelivery;
@property (nonatomic) NSInteger methodId;
@end


SWIFT_CLASS("_TtC10GootenCore7GTNSize")
@interface GTNSize : NSObject
@property (nonatomic) NSInteger width;
@property (nonatomic) NSInteger height;
@end


SWIFT_CLASS("_TtC10GootenCore8GTNSpace")
@interface GTNSpace : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) NSInteger index;
@property (nonatomic) NSInteger finalX1;
@property (nonatomic) NSInteger finalX2;
@property (nonatomic) NSInteger finalY1;
@property (nonatomic) NSInteger finalY2;
@property (nonatomic, copy) NSArray<GTNLayer *> * _Nonnull layers;
@end


SWIFT_CLASS("_TtC10GootenCore11GTNUserInfo")
@interface GTNUserInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull languageCode;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull countryName;
@property (nonatomic, copy) NSString * _Nonnull currencyFormat;
@property (nonatomic, copy) NSString * _Nonnull currencyCode;
@property (nonatomic, copy) NSString * _Nonnull currencyName;
@end


SWIFT_CLASS("_TtC10GootenCore16GTNVariantOption")
@interface GTNVariantOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull optionId;
@property (nonatomic, copy) NSString * _Nonnull valueId;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull value;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic, copy) NSString * _Nonnull imageType;
@property (nonatomic) NSInteger sortValue;
@end

#pragma clang diagnostic pop
